cv_params: {
    val_ratio: 0,
}
model_name: 'PretrainedModel'
pre_init_pw: True
model_params: {
    debug: True,
    inference: "segmental",
    segmental: True,
    start_prior: True,
    end_prior: True
}
plot_predictions: True
