cv_params: {
    val_ratio: 0.25,
    n_splits: 5,
    shuffle: True
}
model_name: 'PretrainedModel'
pre_init_pw: True
model_params: {
    debug: True,
    inference: "segmental",
    segmental: True
}
transitions: {
    0: [1],
    1: [0]
}
plot_predictions: True
