cv_params: {
    val_ratio: 0.25,
    n_splits: 5,
    shuffle: True
}
model_name: 'PretrainedModel'
pre_init_pw: True
model_params: {
    debug: True,
    # conv_len: 25,
    inference: "segmental",
    segmental: True
}
transitions: {
    0: [1, 2],
    1: [2, 3],
    2: [1, 3],
    3: [],
}
train_params: {
    n_iter: 200,
    learning_rate: 0.1,
    pretrain: True,
    update_period: 1,
    verbose: False,
    # gradient_method: 'adagrad',
    gradient_method: 'sgd',
    decay_rate: 0.99,
    batch_size: 5,
    C: 1.0
}
plot_predictions: True
