corpus_name: 'child'
display_summary_img: False
background_removal_options: {
    mask_left_side: 0.4,
    plane_distance_thresh: 10
}
segment_image_options: {
    slic: False,
    target_removal_method: 'lower_right'
}
