model_name: 'LatticeCRF'
batch_size: 1
learning_rate: 0.001
cv_params: {
    val_ratio: 0.25,
    n_splits: 5,
    shuffle: True
}
train_params: {
    num_epochs: 1,
    test_metric: 'Accuracy'
}
model_params: {
}
plot_predictions: True
